# Generated by Django 4.0.2 on 2022-02-13 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ContainerId', models.PositiveBigIntegerField()),
                ('MaxCapacity', models.PositiveBigIntegerField()),
                ('CurrentCapacity', models.PositiveBigIntegerField()),
                ('Temperature', models.PositiveBigIntegerField()),
                ('Type', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ContainerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ContainerTypeId', models.PositiveBigIntegerField()),
                ('Type', models.CharField(max_length=64)),
            ],
        ),
    ]
