# Generated by Django 4.0.2 on 2022-04-22 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='ContainerId',
            field=models.CharField(max_length=64),
        ),
    ]
