# Generated by Django 4.0.2 on 2022-04-22 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_container_containerid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cli_uuid', models.CharField(max_length=64)),
                ('cli_first_name', models.CharField(max_length=64)),
                ('cli_last_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.RenameField(
            model_name='container',
            old_name='ContainerId',
            new_name='container_id',
        ),
        migrations.RenameField(
            model_name='container',
            old_name='CurrentCapacity',
            new_name='current_capacity',
        ),
        migrations.RenameField(
            model_name='container',
            old_name='MaxCapacity',
            new_name='max_capacity',
        ),
        migrations.RenameField(
            model_name='container',
            old_name='Temperature',
            new_name='temperature',
        ),
        migrations.RenameField(
            model_name='container',
            old_name='Type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='containertype',
            old_name='ContainerTypeId',
            new_name='container_type_id',
        ),
        migrations.RenameField(
            model_name='containertype',
            old_name='Type',
            new_name='type',
        ),
    ]
