# Generated by Django 4.0.2 on 2022-04-23 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_product_client_cli_age_client_cli_cellphone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='current_capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='container',
            name='max_capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='container',
            name='temperature',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='container',
            name='type',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='containertype',
            name='container_type_id',
            field=models.IntegerField(default=0),
        ),
    ]
