# Generated by Django 4.0.2 on 2022-04-23 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_container_current_capacity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='container',
            old_name='container_id',
            new_name='container_uuid',
        ),
        migrations.AddField(
            model_name='product',
            name='container_uuid',
            field=models.CharField(default=str, max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_harvest_date',
            field=models.DateField(),
        ),
    ]
