# Generated by Django 4.0.2 on 2022-04-23 01:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_container_id_container_container_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_register_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
