# Generated by Django 4.0.2 on 2022-05-12 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_product_prod_register_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tru_max_capacity', models.IntegerField()),
                ('tru_actual_capacity', models.IntegerField()),
                ('tru_location', models.CharField(max_length=84)),
                ('tru_status', models.CharField(max_length=32)),
                ('tru_placa', models.CharField(max_length=32)),
                ('tru_brand', models.CharField(max_length=32)),
                ('tru_model', models.CharField(max_length=32)),
                ('tru_color', models.CharField(max_length=32)),
                ('tru_truck_number', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='TruckType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truT_id', models.IntegerField()),
                ('truT_type', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_uuid', models.CharField(max_length=64)),
                ('user_password', models.CharField(max_length=32)),
                ('user_email', models.CharField(max_length=64)),
                ('user_direction', models.CharField(max_length=248)),
                ('user_cellphone', models.CharField(max_length=32)),
                ('user_role', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userT_id', models.IntegerField()),
                ('userT_role', models.CharField(max_length=32)),
            ],
        ),
    ]
