# Generated by Django 4.0.2 on 2022-05-15 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_user_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='tru_uuid',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
